services:
  gitlab:
    container_name: gitlab-ce
    image: docker.io/gitlab/gitlab-ce:17.1.1-ce.0
    restart: always
    profiles: [gitlab]
    hostname: gitlablocal.dev
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1'
        gitlab_rails['gitlab_shell_ssh_port'] = 1022
    ports:
      - "80:80"
      - "443:443"
      - "1022:22"
    volumes:
      - "./gitlab/config:/etc/gitlab"
      - "./gitlab/logs:/var/log/gitlab"
      - "./gitlab/data:/var/opt/gitlab"
    networks:
      gitprovider:
        ipv4_address: 10.5.0.5

  runner:
    image: docker.io/gitlab/gitlab-runner:alpine
    profiles: [gitlab]
    restart: always
    container_name: gitlab-runner
    hostname: gitlab-runner.dev
    depends_on:
      - gitlab
    volumes:
      - ./config/gitlab-runner:/etc/gitlab-runner
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
    networks:
      gitprovider:
        ipv4_address: 10.5.0.6

  gitea:
    image: gitea/gitea:1.22.0
    container_name: gitea
    profiles: [gitea]
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      gitprovider:
        ipv4_address: 10.5.0.7
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db

  db:
    image: postgres:16
    profiles: [gitea]
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      gitprovider:
        ipv4_address: 10.5.0.8
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  gitprovider:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1